version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - cd frontend
      - npm install

  build:
    commands:
      - npm run build --configuration=production
      - cd ..

  post_build:
    commands:
      - mkdir -p eb-deploy/dist
      - cp -r frontend/dist/browser/* eb-deploy/dist/
      - cp frontend/package.json frontend/server.js eb-deploy/
      - mkdir -p eb-deploy/.ebextensions
      - |
        cat <<EOF > eb-deploy/.ebextensions/node.config.yml
        option_settings:
          aws:elasticbeanstalk:application:environment:
            NODE_VERSION: 22
        EOF
      - cd eb-deploy
      - npm install --production
      - zip -r ../eb-deploy.zip . -x "*.git*" "node_modules/aws-sdk/*"
      - cd ..
      - aws s3 cp eb-deploy.zip s3://elasticbeanstalk-eu-north-1-996068820846/eb-deploy.zip --region eu-north-1
      - VERSION_LABEL=$(date +%Y%m%d%H%M%S)
      - aws elasticbeanstalk create-application-version \
          --application-name "Reko-rinki" \
          --version-label "$VERSION_LABEL" \
          --source-bundle S3Bucket="elasticbeanstalk-eu-north-1-996068820846",S3Key="eb-deploy.zip" \
          --region eu-north-1
      - aws elasticbeanstalk update-environment \
          --environment-name "Reko-rinki-env" \
          --version-label "$VERSION_LABEL" \
          --region eu-north-1

artifacts:
  files:
    - eb-deploy.zip

