version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - cd frontend
      - npm install

  build:
    commands:
      - npm run build --configuration=production
      - cd ..

  post_build:
    commands:
      - aws s3 sync frontend/dist/browser s3://reko-frontend-bucket/ --delete --region eu-north-1
      - aws cloudfront create-invalidation --distribution-id E246HFIVSS9HOP --paths "/*"

artifacts:
  files:
    - frontend/dist/browser/**/*
