version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - cd backend
      - npm install

  build:
    commands:
      - npm run build || echo "No build script, skipping build step"
      - cd ..

  post_build:
    commands:
      - mkdir -p eb-deploy
      - cp -r backend/* eb-deploy/
      - rm -rf eb-deploy/node_modules
      - cd eb-deploy
      - npm install --production
      - cd ..
      - mkdir -p eb-deploy/.ebextensions
      - |
        cat <<EOF > eb-deploy/.ebextensions/node.config.yml
        option_settings:
          aws:elasticbeanstalk:container:nodejs:
            NodeVersion: 22
        EOF
      - |
        cat <<EOF > eb-deploy/.ebextensions/01-cloudwatch-logs.config
        files:
          "/opt/aws/amazon-cloudwatch-agent/bin/config.json":
            content: |
              {
                "logs": {
                  "logs_collected": {
                    "files": {
                      "collect_list": [
                        {
                          "file_path": "/var/log/web.stdout.log",
                          "log_group_name": "/elasticbeanstalk/Rekorinki",
                          "log_stream_name": "i-055bc07db2d01faae-stdout"
                        },
                        {
                          "file_path": "/var/log/web.stderr.log",
                          "log_group_name": "/elasticbeanstalk/Rekorinki",
                          "log_stream_name": "i-055bc07db2d01faae-stderr"
                        },
                        {
                          "file_path": "/var/log/messages",
                          "log_group_name": "/elasticbeanstalk/Rekorinki",
                          "log_stream_name": "i-055bc07db2d01faae-syslog"
                        }
                      ]
                    }
                  }
                }
              }
        commands:
          "01-start-cloudwatch-agent":
            command: "/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json -s"
        EOF
      - cd eb-deploy
      - zip -r ../eb-deploy.zip . -x "*.git*" "node_modules/aws-sdk/*"
      - cd ..
      - aws s3 cp eb-deploy.zip s3://elasticbeanstalk-eu-north-1-996068820846/eb-deploy.zip --region eu-north-1
      - aws elasticbeanstalk create-application-version --application-name "Reko-rinki" --version-label "$CODEBUILD_RESOLVED_SOURCE_VERSION" --source-bundle S3Bucket="elasticbeanstalk-eu-north-1-996068820846",S3Key="eb-deploy.zip" --region eu-north-1
      - aws elasticbeanstalk update-environment --environment-name "Reko-rinki-env" --version-label "$CODEBUILD_RESOLVED_SOURCE_VERSION" --region eu-north-1

artifacts:
  files:
    - eb-deploy.zip
