# POST http://localhost:3000/register HTTP/1.1
# Content-Type: application/json

# {
#   "tuottaja": false,
#   "kayttajatunnus": "a123",
#   "salasana": "Testi123",
#   "etunimi": "a",
#   "sukunimi": "a",
#   "puhelinnro": "+35840012345678",
#   "sahkoposti": "a@jamk.fi",
#   "katuosoite": "Matarankatu 1",
#   "postinumero": "40320",
#   "postitoimipaikka": "Jyväskylä",
#   "paikkakunta": "Jyväskylä"
# }

post http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
"tuottaja": false,
"sahkoposti": "a@jamk.fi",
"salasana": "Testi1234"
}
