POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json

{
  "tuottaja": false,
  "kayttajatunnus": "Testikäyttäjä100",
  "salasana": "Testi123",
  "etunimi": "testi500",
  "sukunimi": "testi",
  "puhelinnro": "+35850123456789",
  "sahkoposti": "testi100@jamk.com",
  "katuosoite": "Matarankatu 1",
  "postinumero": "40320",
  "postitoimipaikka": "Jyväskylä",
  "paikkakunta": "Jyväskylä"
}
