name: CICD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Create Dummy App
        run: |
          echo "Hello from GitHub Actions" > index.html
          zip -r nodejs-app-build.zip index.html

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'RekoRinki'
          environment_name: 'RekoRinki-env'
          version_label: ${{ github.sha }}
          region: eu-north-1
          deployment_package: nodejs-app-build.zip
