name: CICD

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      - name: Package Frontend for Elastic Beanstalk
        run: |
          mkdir -p frontend/.ebextensions
          echo "option_settings:
          aws:elasticbeanstalk:environment:proxy:staticfiles:
          /: build" > frontend/.ebextensions/static.config.yml
          cd frontend
          zip -r ../frontend-build.zip server.js package.json build .ebextensions -x "*.git*" "node_modules/*"
          cd ..

      - name: Deploy Frontend to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'Reko'
          environment_name: 'Reko-env'
          version_label: ${{ github.sha }}
          region: eu-north-1
          deployment_package: frontend-build.zip
          use_existing_version_if_available: false
          wait_for_deployment: true
          wait_for_environment_recovery: true



  # deploy-backend:
  #   name: Deploy Backend
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Source
  #       uses: actions/checkout@v4

  #     - name: Set up Node.js (tai muu runtime)
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '22'

  #     - name: Install Backend Dependencies
  #       working-directory: ./backend
  #       run: npm install

  #     - name: Run Backend Tests
  #       working-directory: ./backend
  #       run: npm test || echo "No backend tests defined"

  #     - name: Generate Backend Deployment Package
  #       run: |
  #         cd backend
  #         zip -r ../backend-build.zip . -x "*.git*" "node_modules/*"

  #     - name: Deploy Backend to Elastic Beanstalk
  #       uses: einaregilsson/beanstalk-deploy@v22
  #       with:
  #         aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
  #         aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         application_name: 'Reko'
  #         environment_name: 'Reko-env'
  #         version_label: ${{ github.sha }}
  #         region: eu-north-1
  #         deployment_package: backend-build.zip
